// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';

export function ConnectCreate(arg1:define.Connection):Promise<define.M>;

export function ConnectDel(arg1:string):Promise<define.M>;

export function ConnectionEdit(arg1:define.Connection):Promise<define.M>;

export function ConnectionList():Promise<define.M>;
