// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectCreate(arg1) {
  return window['go']['main']['App']['ConnectCreate'](arg1);
}

export function ConnectDel(arg1) {
  return window['go']['main']['App']['ConnectDel'](arg1);
}

export function ConnectionEdit(arg1) {
  return window['go']['main']['App']['ConnectionEdit'](arg1);
}

export function ConnectionList() {
  return window['go']['main']['App']['ConnectionList']();
}
