// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';

export function AddHash(arg1:define.AddHash):Promise<define.M>;

export function AddString(arg1:define.AddUpdateString):Promise<define.M>;

export function ConnectCreate(arg1:define.Connection):Promise<define.M>;

export function ConnectDel(arg1:string):Promise<define.M>;

export function ConnectionEdit(arg1:define.Connection):Promise<define.M>;

export function ConnectionList():Promise<define.M>;

export function DbInfo(arg1:string):Promise<define.M>;

export function DbList(arg1:string):Promise<define.M>;

export function DelHash(arg1:define.DelHash):Promise<define.M>;

export function DelHashItem(arg1:define.DelHashItem):Promise<define.M>;

export function DelString(arg1:define.DelString):Promise<define.M>;

export function SearchValues(arg1:define.SearchKey):Promise<define.M>;

export function UpdateHashItem(arg1:define.UpdateHashItem):Promise<define.M>;

export function UpdateString(arg1:define.AddUpdateString):Promise<define.M>;
