// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHash(arg1) {
  return window['go']['main']['App']['AddHash'](arg1);
}

export function AddString(arg1) {
  return window['go']['main']['App']['AddString'](arg1);
}

export function ConnectCreate(arg1) {
  return window['go']['main']['App']['ConnectCreate'](arg1);
}

export function ConnectDel(arg1) {
  return window['go']['main']['App']['ConnectDel'](arg1);
}

export function ConnectionEdit(arg1) {
  return window['go']['main']['App']['ConnectionEdit'](arg1);
}

export function ConnectionList() {
  return window['go']['main']['App']['ConnectionList']();
}

export function DbInfo(arg1) {
  return window['go']['main']['App']['DbInfo'](arg1);
}

export function DbList(arg1) {
  return window['go']['main']['App']['DbList'](arg1);
}

export function DelHash(arg1) {
  return window['go']['main']['App']['DelHash'](arg1);
}

export function DelHashItem(arg1) {
  return window['go']['main']['App']['DelHashItem'](arg1);
}

export function DelString(arg1) {
  return window['go']['main']['App']['DelString'](arg1);
}

export function SearchCli(arg1) {
  return window['go']['main']['App']['SearchCli'](arg1);
}

export function SearchValues(arg1) {
  return window['go']['main']['App']['SearchValues'](arg1);
}

export function UpdateHashItem(arg1) {
  return window['go']['main']['App']['UpdateHashItem'](arg1);
}

export function UpdateString(arg1) {
  return window['go']['main']['App']['UpdateString'](arg1);
}
